version: "3.9"
services:
  blog:
    build:
      context: .
      target: build
    command: sh -c 'bundle exec jekyll serve --drafts --incremental --force_polling --livereload -H 0.0.0.0'
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/src
